class SignatureMismatchError(Exception):
    ...

class IncorrectArgumentsOrderError(Exception):
    ...

class SignatureNotFoundError(Exception):
    ...

class UnsupportedSignatureError(Exception):
    ...
